# Generated by Django 6.0.7 on 2026-09-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст запитання')),
                ('option1', models.CharField(max_length=200, verbose_name='Варіант 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Варіант 2')),
                ('option3', models.CharField(max_length=200, verbose_name='Варіант 3')),
                ('option4', models.CharField(max_length=200, verbose_name='Варіант 4')),
                ('correct_option', models.IntegerField(choices=[(1, 'Варіант 1'), (2, 'Варіант 2'), (3, 'Варіант 3'), (4, 'Варіант 4')], verbose_name='Правильна відповідь')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Вікторина')),
            ],
        ),
    ]
